apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - name: ftp-data
      port: 20
    - name: ftp-connection
      port: 21
    - name: pftp-data-0
      port: 44000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps_image
          imagePullPolicy: Never
          ports:
          - containerPort: 44000
          - containerPort: 21
          - containerPort: 20